### ISSUE TITLE
Constant Resident Set Size

### ISSUE THREAD

**Issue by sukritkalra** [ericchiang/memplot#1]
Hi!

I tried out `memtop` to run the sample program in your `README.md`. But, my RSS stays at 612 MB and the graph is a straight line parallel to X-Axis.

![image](https://cloud.githubusercontent.com/assets/4013287/3141415/304ea394-e97a-11e3-9679-ef1991279537.png)

This is the same for any process that I create. What could be the issue here?

**Comment by ericchiang** [comment]
The actual usage tracking goes through the [psutil](http://pythonhosted.org/psutil/) library so I suspect this is an issue with that package. What os are you running? So far I've only tested memplot on OS X.

**Comment by sukritkalra** [comment]
Ubuntu 12.04 LTS. 

I checked out the psutil package by creating various processes with `subprocess.Popen` and checking the return value of their RSS at regular intervals. All of those stayed at 612 MB during their execution. Although, if I attach `psutil` to an existing process, like Chrome, it is able to report that its RSS varies with time. 

Also, any particular reason why you're running the loop indefinitely? After execution, the RSS and VMS values returned by the subprocess turn 0 and the loop is never broken. I fixed that in my fork by running the loop only until the process turns into a zombie. Can you check that out and if there are no errors, I could issue a pull request. (This does not solve the constant RSS problem on my system though)

**Comment by ericchiang** [comment]
Hmm, maybe `shell=True` is messing it up? Could you try replacing [this line](https://github.com/sukritkalra/memplot/blob/master/memplot/memplot.py#L16) with:

``` python
p = subprocess.Popen(cmd.split())
```

The loop runs indefinitely just as a hack more than for any particular reason.

Tested your fork and looks like everything works great. Love to have that pull request.

**Comment by sukritkalra** [comment]
Yes. That did and fixed it. Also made the code more secure.

![image2](https://cloud.githubusercontent.com/assets/4013287/3142316/578c08d2-e9b8-11e3-937f-69ad2d6e3ed0.png)

Issued a pull request.

**Comment by ericchiang** [comment]
Awesome, thanks for the help

**Comment by sukritkalra** [comment]
Great project! Will see if I can find and fix more bugs. :)
